Replacing OMAS with IMASDD everywhere
Tested this but got following error:
```
(base) gupta@F-CJXNMY7L7 SD4SOLPS.jl % julia --project test/runtests.jl
Test Summary:         | Pass  Total  Time
lightweight_utilities |    4      4  1.0s
Test Summary: | Pass  Total  Time
actuator      |    2      2  1.7s
core_profile_extension: Error During Test at /Users/gupta/Git/ProjectTorreyPines/SD4SOLPS.jl/test/runtests.jl:166
  Got exception outside of a @test
  UndefVarError: `gradient` not defined
  Stacktrace:
   [1] extrapolate_core(edge_rho::Vector{Float64}, edge_quantity::Vector{Float64}, rho_output::Vector{Float64})
     @ SD4SOLPS ~/Git/ProjectTorreyPines/SD4SOLPS.jl/src/supersize_profile.jl:58
   [2] macro expansion
     @ ~/Git/ProjectTorreyPines/SD4SOLPS.jl/test/runtests.jl:171 [inlined]
   [3] macro expansion
     @ /Applications/Julia-1.9.app/Contents/Resources/julia/share/julia/stdlib/v1.9/Test/src/Test.jl:1498 [inlined]
   [4] top-level scope
     @ ~/Git/ProjectTorreyPines/SD4SOLPS.jl/test/runtests.jl:168
   [5] include(mod::Module, _path::String)
     @ Base ./Base.jl:457
   [6] exec_options(opts::Base.JLOptions)
     @ Base ./client.jl:307
   [7] _start()
     @ Base ./client.jl:522
Test Summary:          | Error  Total  Time
core_profile_extension |     1      1  0.5s
ERROR: LoadError: Some tests did not pass: 0 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /Users/gupta/Git/ProjectTorreyPines/SD4SOLPS.jl/test/runtests.jl:165
```

For testing, following versions of the pacjages were used (these are the points where IMASDD was used instead of OMAS):
GGDUtils: https://github.com/ProjectTorreyPines/GGDUtils.jl/commit/b11ad1581718a7bf4a50c2551b2a2a7b84a3394e
SOLPS2IMAS: https://github.com/ProjectTorreyPines/SOLPS2IMAS.jl/commit/f843e6a64ccd597e0eb77ab4f953c922614d99e4

The main issue is that OMAS.gradient() function is defined in https://github.com/ProjectTorreyPines/OMAS.jl/blob/master/src/math.jl
but no such function exists in IMASDD.